---
- name: Verify cluster
  hosts: k8s_master
  become: yes

  tasks:
    - name: Show nodes
      shell: kubectl --kubeconfig /etc/kubernetes/admin.conf get nodes -o wide
      register: nodes

    - debug:
        msg: "{{ nodes.stdout }}"

