---
- name: Verify Kubernetes cluster
  hosts: k8s_master
  become: yes
  tasks:
    - name: Create test namespace
      ansible.builtin.shell: |
        kubectl create namespace test --dry-run=client -o yaml | kubectl apply -f -


    - name: Deploy nginx test app
      ansible.builtin.shell: |
        kubectl create deployment nginx-test --image=nginx:alpine -n test
